source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'autoLog_Example', :exclusive => true do
  pod "autoLog", :path => "../"
end

target 'autoLog_Tests', :exclusive => true do
  pod "autoLog", :path => "../"

  
end
